Secret added to console
cwc-products/simpleOne pull request #32
Opened 2018-10-26 08:01 UTC by muralidhar-chintada

#24 @suvarna-tammina  I have added the "SECRET" to app.js

2018-10-26 08:13 UTC, suvarna-tammina requested changes
@muralidhar-chintada Add arrow function instead console. look at #23 example and follow that.

2018-10-26 08:18 UTC, muralidhar-chintada commented
@suvarna-tammina I have made the changes required. Please check it once.

2018-10-26 11:05 UTC, cwc-products submitted a review, later dismissed

2018-10-26 11:05 UTC, cwc-products commented on go-ducks.js
> +const consumables = [() => ' SECRET'];
@muralidhar-chintada It looks like there is a space before SECRET.  Please remove the space.

2018-10-29 06:06 UTC, suvarna-tammina approved these changes
@muralidhar-chintada Looks Good

2018-10-29 06:22 UTC, suvarna-tammina commented on go-ducks.js
> +const consumables = [() => ' SECRET'];
Resolved.

2018-10-29 06:23 UTC, suvarna-tammina approved these changes
@muralidhar-chintada  Resolved

2018-10-29 06:26 UTC, merged